#include "common.h"

const char ERRS_TEXT[][MAX_STR_LEN] =
{ [ERR_SUCCESS] = "ERR_SUCCESS",
  [ERR_INTERRUPT] = "ERR_INTERRUPT",
  [ERR_INVALID_OPCODE] = "ERR_INVALID_OPCODE",
  [ERR_STACK_OVERFLOW] = "ERR_STACK_OVERFLOW",
  [ERR_EMPTY_STACK] = "ERR_EMPTY_STACK"
};
